#include "../Pyrebox_libcalls.h"

libcall_info_t USP10_info[] = {
	{ "ScriptGetFontScriptTags",6,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "cMaxTags", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "pScriptTags", NKT_DBFUNDTYPE_UnsignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{5, "pcTags", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptString_pSize",1,
	{ 
		{-1, "Return value", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagSIZE", 64, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
	}
	},
	{ "ScriptPlace",9,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "pwGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{3, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{5, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, INOUT },
		{6, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{7, "pGoffset", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagGOFFSET", 64, INOUT },
		{8, "pABC", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "_ABC", 96, INOUT },
	}
	},
	{ "ScriptShape",10,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "pwcChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{3, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "cMaxGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{5, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, INOUT },
		{6, "pwOutGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
		{7, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
		{8, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, INOUT },
		{9, "pcGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetCMap",6,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "pwcInChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{3, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "dwFlags", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "pwOutGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
	}
	},
	{ "ScriptStringXtoCP",4,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{1, "iX", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "piCh", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{3, "piTrailing", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetFontLanguageTags",7,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "cMaxTags", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{5, "pLangsysTags", NKT_DBFUNDTYPE_UnsignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{6, "pcTags", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptPositionSingleGlyph",12,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "tagFeature", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{6, "lParameter", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{7, "wGlyphId", NKT_DBFUNDTYPE_UnsignedWord, 0, 2, IN },
		{8, "iAdvance", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{9, "GOffset", NKT_DBOBJCLASS_Struct, "tagGOFFSET", 64, IN },
		{10, "piOutAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{11, "pOutGoffset", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagGOFFSET", 64, INOUT },
	}
	},
	{ "ScriptShapeOpenType",16,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, INOUT },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "rcRangeChars", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{6, "rpRangeProperties", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_PointerPointer, "textrange_properties", 64, IN },
		{7, "cRanges", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{8, "pwcChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{9, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{10, "cMaxGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{11, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
		{12, "pCharProps", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "script_charprop", 16, INOUT },
		{13, "pwOutGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
		{14, "pOutGlyphProps", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "script_glyphprop", 32, INOUT },
		{15, "pcGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptItemizeOpenType",8,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "pwcInChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{1, "cInChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cMaxItems", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "psControl", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_CONTROL", 32, IN },
		{4, "psState", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_STATE", 16, IN },
		{5, "pItems", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ITEM", 64, INOUT },
		{6, "pScriptTags", NKT_DBFUNDTYPE_UnsignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{7, "pcItems", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptXtoCP",9,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "iX", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{1, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{4, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{5, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{6, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{7, "piCP", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{8, "piTrailing", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetLogicalWidths",7,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{1, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "piGlyphWidth", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{4, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{5, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{6, "piDx", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptStringOut",8,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{1, "iX", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "iY", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "uOptions", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "prc", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagRECT", 128, IN },
		{5, "iMinSel", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{6, "iMaxSel", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{7, "fDisabled", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
	}
	},
	{ "ScriptString_pcOutChars",1,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
	}
	},
	{ "ScriptApplyDigitSubstitution",3,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "psds", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_DIGITSUBSTITUTE", 96, IN },
		{1, "psc", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_CONTROL", 32, INOUT },
		{2, "pss", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_STATE", 16, INOUT },
	}
	},
	{ "ScriptApplyLogicalWidth",9,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "piDx", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{1, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{4, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{5, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{6, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{7, "pABC", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "_ABC", 96, INOUT },
		{8, "piJustify", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptStringCPtoX",4,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{1, "icp", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "fTrailing", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "pX", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptBreak",4,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "pwcChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{1, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "psla", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_LOGATTR", 8, INOUT },
	}
	},
	{ "ScriptGetProperties",2,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ppSp", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer | NKT_DBOBJCLASS_Pointer | NKT_DBOBJCLASS_Pointer, "SCRIPT_PROPERTIES", 64, INOUT },
		{1, "piNumScripts", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptCPtoX",9,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "iCP", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{1, "fTrailing", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{5, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{6, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{7, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{8, "piX", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetGlyphABCWidth",4,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "wGlyph", NKT_DBFUNDTYPE_UnsignedWord, 0, 2, IN },
		{3, "pABC", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "_ABC", 96, INOUT },
	}
	},
	{ "ScriptGetFontFeatureTags",8,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "cMaxTags", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{6, "pFeatureTags", NKT_DBFUNDTYPE_UnsignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{7, "pcTags", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptPlaceOpenType",18,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, INOUT },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "rcRangeChars", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{6, "rpRangeProperties", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_PointerPointer, "textrange_properties", 64, IN },
		{7, "cRanges", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{8, "pwcChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{9, "pwLogClust", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{10, "pCharProps", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "script_charprop", 16, IN },
		{11, "cChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{12, "pwGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{13, "pGlyphProps", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "script_glyphprop", 32, IN },
		{14, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{15, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{16, "pGoffset", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagGOFFSET", 64, INOUT },
		{17, "pABC", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "_ABC", 96, INOUT },
	}
	},
	{ "ScriptStringGetLogicalWidths",2,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{1, "piDx", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptJustify",6,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "psva", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_VISATTR", 16, IN },
		{1, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{2, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "iDx", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "iMinKashida", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{5, "piJustify", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetFontAlternateGlyphs",10,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "tagFeature", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{6, "wGlyphId", NKT_DBFUNDTYPE_UnsignedWord, 0, 2, IN },
		{7, "cMaxAlternates", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{8, "pAlternateGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
		{9, "pcAlternates", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptItemize",7,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "pwcInChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{1, "cInChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "cMaxItems", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "psControl", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_CONTROL", 32, IN },
		{4, "psState", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_STATE", 16, IN },
		{5, "pItems", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ITEM", 64, INOUT },
		{6, "pcItems", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptStringFree",1,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "pssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, IN },
	}
	},
	{ "ScriptString_pLogAttr",1,
	{ 
		{-1, "Return value", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_LOGATTR", 8, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
	}
	},
	{ "ScriptCacheGetHeight",3,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "tmHeight", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptTextOut",14,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "x", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "y", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "fuOptions", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "lprc", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagRECT", 128, IN },
		{6, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{7, "pwcReserved", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{8, "iReserved", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{9, "pwGlyphs", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{10, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{11, "piAdvance", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{12, "piJustify", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{13, "pGoffset", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tagGOFFSET", 64, IN },
	}
	},
	{ "ScriptStringGetOrder",2,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{1, "puOrder", NKT_DBFUNDTYPE_UnsignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptLayout",4,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "cRuns", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{1, "pbLevel", NKT_DBFUNDTYPE_UnsignedByte | NKT_DBOBJCLASS_Pointer, 0, 1, IN },
		{2, "piVisualToLogical", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
		{3, "piLogicalToVisual", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, INOUT },
	}
	},
	{ "ScriptGetFontProperties",3,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "sfp", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "SCRIPT_FONTPROPERTIES", 128, INOUT },
	}
	},
	{ "ScriptRecordDigitSubstitution",2,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "Locale", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psds", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_DIGITSUBSTITUTE", 96, INOUT },
	}
	},
	{ "ScriptIsComplex",3,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "pwcInChars", NKT_DBFUNDTYPE_WideChar | NKT_DBOBJCLASS_Pointer, 0, 2, IN },
		{1, "cInChars", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{2, "dwFlags", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
	}
	},
	{ "ScriptStringAnalyse",13,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "pString", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
		{2, "cString", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{3, "cGlyphs", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{4, "iCharset", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{5, "dwFlags", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{6, "iReqWidth", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{7, "psControl", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_CONTROL", 32, IN },
		{8, "psState", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_STATE", 16, IN },
		{9, "piDx", NKT_DBFUNDTYPE_SignedDoubleWord | NKT_DBOBJCLASS_Pointer, 0, 4, IN },
		{10, "pTabdef", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_TABDEF", 128, IN },
		{11, "pbInClass", NKT_DBFUNDTYPE_UnsignedByte | NKT_DBOBJCLASS_Pointer, 0, 1, IN },
		{12, "pssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, IN },
	}
	},
	{ "ScriptSubstituteSingleGlyph",9,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "hdc", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{1, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
		{2, "psa", NKT_DBOBJCLASS_Struct | NKT_DBOBJCLASS_Pointer, "tag_SCRIPT_ANALYSIS", 32, IN },
		{3, "tagScript", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{4, "tagLangSys", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{5, "tagFeature", NKT_DBFUNDTYPE_UnsignedDoubleWord, 0, 4, IN },
		{6, "lParameter", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, IN },
		{7, "wGlyphId", NKT_DBFUNDTYPE_UnsignedWord, 0, 2, IN },
		{8, "pwOutGlyphId", NKT_DBFUNDTYPE_UnsignedWord | NKT_DBOBJCLASS_Pointer, 0, 2, INOUT },
	}
	},
	{ "ScriptStringValidate",1,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "ssa", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_Pointer, 0, 0, IN },
	}
	},
	{ "ScriptFreeCache",1,
	{ 
		{-1, "Return value", NKT_DBFUNDTYPE_SignedDoubleWord, 0, 4, INOUT },
		{0, "psc", NKT_DBFUNDTYPE_Void | NKT_DBOBJCLASS_PointerPointer, 0, 0, INOUT },
	}
	},
};

int USP10arraySize = (sizeof(USP10_info) / sizeof(USP10_info[0]));